name: iOS build
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./flutter_ios_ci_exp
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        flutter: [stable]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter }}
      - run: dart pub get
      - run: dart pub global activate dev_test
      - run: dart pub global run dev_test:run_ci